name: 'Github Action Accelerator Template'
description: 'simple typescript template for building GitHub Actions'
author: "ivankatliarchuk <https://github.com/ivankatliarchuk>"
inputs:
  name:
    description: 'input description here'
    default: 'World'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: "yellow"
  icon: "bell"
