name: release-drafter

on:
  push:
    branches: [$default-branch]
  workflow_dispatch:

jobs:
  draft-a-release:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5.15.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
