name: release-drafter

on:
  push:
    branches: [$default-branch]
  workflow_dispatch:
    inputs:
      prerelease:
        description: Is this a pre-release
        required: true
        default: true
      publish:
        description: Publish release
        required: false
        default: false

jobs:
  draft-a-release:
    runs-on: ubuntu-latest
    steps:

      - name: release-draft
        uses: release-drafter/release-drafter@v5.15.0
        if: "!contains(github.event.head_commit.message, 'skip')"
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: ${{ github.event.inputs.publish }}
          prerelease: ${{ github.event.inputs.prerelease }}

      - name: check-version
        run: |
          echo "release it: ${{ github.event.inputs.prerelease }}"
          echo "name: $(steps.release.outputs.name)"
          echo "tag: $(steps.release.outputs.tag_name)"
